Repository Turbo87/intellij-emberjs, pull requests merged in 2019-12, with the labels that each got.

#282 Replace the deprecated `LightPlatformCodeInsightFixtureTestCase` with `BasePlatformTestCase`
  src/test/kotlin/com/emberjs/hbs/HbsPatternsTest.kt
  src/test/kotlin/com/emberjs/index/EmberNameIndexTest.kt
  src/test/kotlin/com/emberjs/navigation/EmberGotoRelatedProviderTest.kt
  src/test/kotlin/com/emberjs/navigation/EmberTestFinderTest.kt
  src/test/kotlin/com/emberjs/translations/EmberI18nFoldingBuilderTest.kt
  src/test/kotlin/com/emberjs/translations/EmberI18nIndexTest.kt
  src/test/kotlin/com/emberjs/translations/EmberI18nTest.kt
  src/test/kotlin/com/emberjs/translations/EmberIntlFoldingBuilderTest.kt
  src/test/kotlin/com/emberjs/translations/EmberIntlIndexTest.kt
  src/test/kotlin/com/emberjs/translations/EmberIntlTest.kt
  src/test/kotlin/com/emberjs/translations/EmberTranslationHbsReferenceTest.kt
Labels: internal

#283 Setup CI on GitHub Actions
  .github/workflows/ci.yml
Labels: internal

#284 Remove AppVeyor config
  appveyor.yml
Labels: internal

#285 Use `kotlin-stdlib-jdk8` dependency instead of `kotlin-stdlib`
  build.gradle
Labels: internal

#286 Update IntelliJ to v2019.3
  build.gradle
Labels: enhancement

#287 Update Gradle to v6.0.1
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: internal

#291 fix: ensure that we implement `executable(pkg: NodePage)` as the old impl was deprecated
  src/main/kotlin/com/emberjs/cli/EmberCliProjectGenerator.kt
Labels: bug

#292 Replace user/password authentication with `intellijPublishToken`
  build.gradle
  gradle.properties
Labels: internal

#293 Angle bracket autocomplete and goto references
  src/main/kotlin/com/emberjs/EmberTagNameProvider.kt
  src/main/kotlin/com/emberjs/EmberXmlElementDescriptor.kt
  src/main/kotlin/com/emberjs/EmberXmlElementDescriptorProvider.kt
  src/main/kotlin/com/emberjs/resolver/EmberName.kt
  src/main/resources/META-INF/plugin.xml
  src/test/kotlin/com/emberjs/resolver/EmberNameTest.kt
Labels: enhancement
