Repository Turbo87/intellij-emberjs, pull requests merged in 2023-12, with the labels that each got.

#501 Update IntelliJ to 2023.3
  build.gradle.kts
Labels: enhancement

#502 Remove obsolete `Process` extensions
  src/main/kotlin/com/emberjs/cli/YesThread.kt
  src/main/kotlin/com/emberjs/utils/ProcessExtensions.kt
Labels: internal

#503 Replace deprecated `toUpper/LowerCase()` fns
  src/main/kotlin/com/emberjs/EmberFileType.kt
  src/main/kotlin/com/emberjs/resolver/EmberName.kt
  src/main/kotlin/com/emberjs/utils/EmberStringUtils.kt
Labels: internal

#505 Fix "No display name is specified for configurable" issue
  src/main/resources/META-INF/plugin.xml
Labels: bug
